"""AddAutocremetialToTables

Revision ID: 224cff558bc0
Revises: 1e64b4e36877
Create Date: 2025-04-17 16:21:16.359451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224cff558bc0'
down_revision: Union[str, None] = '1e64b4e36877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_time_slots_self_id'), 'time_slots', ['self_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_slots_self_id'), table_name='time_slots')
    # ### end Alembic commands ###
