"""InitialMigration

Revision ID: 9e6ef596abc2
Revises: 
Create Date: 2025-04-16 05:50:41.250758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6ef596abc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('self_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('subjects', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('requisites', sa.String(), nullable=False),
    sa.Column('telegram_tag', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('discord_tag', sa.String(collation='NOCASE'), nullable=False),
    sa.PrimaryKeyConstraint('self_id')
    )
    op.create_index(op.f('ix_teachers_self_id'), 'teachers', ['self_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('self_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('self_id')
    )
    op.create_table('students',
    sa.Column('self_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('parent_name', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('parent_contact', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('student_contact', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('payment_status', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.self_id'], ),
    sa.PrimaryKeyConstraint('self_id')
    )
    op.create_index(op.f('ix_students_self_id'), 'students', ['self_id'], unique=False)
    op.create_table('lessons',
    sa.Column('self_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.self_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.self_id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.self_id'], ),
    sa.PrimaryKeyConstraint('self_id')
    )
    op.create_index(op.f('ix_lessons_self_id'), 'lessons', ['self_id'], unique=False)
    op.create_table('reminders',
    sa.Column('self_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trigger_time', sa.Time(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.self_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.self_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('self_id')
    )
    op.create_index(op.f('ix_reminders_self_id'), 'reminders', ['self_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_self_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_lessons_self_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_students_self_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_teachers_self_id'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
